---
title: "Metagenomic Feature Counts"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE)
options(scipen=999)

library(ggplot2)
library(reshape2)
library(stringr)
library(cowplot)
library(vegan)
library(ggrepel)
library(foreach)

features=commandArgs(trailingOnly=T)[1]
features=strsplit(features,",")[[1]]

dir=commandArgs(trailingOnly = T)[2]

first=read.table(paste0(dir,"/",features[1],"_combined_counts.tsv"),header=T,row.names=1,sep="\t")

featsum=function(feature,direct){
   cat("# ",feature,"\n")
   data=read.table(paste0(dir,"/",feature,"_combined_counts.tsv"),header=T,row.names=1,sep="\t",comment.char = "",quote = "")
   cat("Identified **`",nrow(data),"`** unique ",feature," features across all samples.\n\n")
   #order samples alphabetically
   data=data[,order(colnames(data))]
   #plot the top 10 of each feature, particularly useful for taxa (or all if <10)
   cat("Relative abundance plot for top ",feature," (mean abundance):\n\n")
   abund=t(data)/colSums(data)
   means=colMeans(abund)
   abund=abund[,order(means,decreasing = T)]
   top=data.frame(abund)
   colnames(top)=paste0("...",str_sub(colnames(top), start= -30))
   if(ncol(top)>11){
       top=top[,1:10]
       top$Other=rowSums(abund[,11:ncol(abund)])
   }
   top$Sample=rownames(top)
   melted=melt(top,id="Sample")
   colnames(melted)=c("Sample","Feature","Abundance")
   fplot=ggplot(melted,aes(Sample,Abundance,fill=Feature))+geom_bar(stat="identity")+
     scale_fill_brewer(type = "div", palette=9)+coord_flip()
   plot(fplot)
   cat("\n\n")
   #pca of samples based on these features
   cat("PCA of samples based on ",feature," abundances:\n\n")
   pca=prcomp(abund)
   pplot=qplot(pca$x[,1],pca$x[,2],color=as.factor(c(1:nrow(pca$x))))+xlab("PC1")+ylab("PC2")+guides(color=F)+
     scale_color_manual(values=rainbow(nrow(pca$x)))
   plot(pplot)
   cat("\n\n")
   #rarefactin plot
   cat(paste0("Rarefaction curves for counts assigned to ",feature," (labelling, upto 10, lowest samples):"))
   sampmax=colSums(data)
   raredepths=round(c(seq(from=1,to=max(sampmax),by=(max(sampmax)-1)/20)))
   vals=matrix(nrow=length(raredepths),ncol=ncol(data))
   foreach(i=1:length(raredepths)) %dopar% {
     depth=raredepths[i]
     res=rarefy(round(t(data)), depth)
     res[sampmax<depth]=NA
     vals[i,]=res
   }
   colnames(vals)=colnames(data)
   rownames(vals)=raredepths
   raremelt=melt(vals)
   colnames(raremelt)=c("Depth","Sample","Richness")
   raremelt=raremelt[!is.na(raremelt$Richness),]
   labels=data.frame(Sample=colnames(data),Depth=sampmax,Rich=apply(vals,2,function(x){max(x,na.rm = T)}))
   labels$Sample=ifelse(rank(labels$Depth)<11,as.character(labels$Sample),NA)
   rplot=ggplot(raremelt,aes(x=Depth,y=Richness,color=Sample))+geom_line()+guides(color=F)+
     geom_label_repel(data=labels,aes(x=Depth,y=Rich,label=Sample))
   plot(rplot)
}

```

# Overview

**`r length(features)`** features counted across **`r ncol(first)`** samples.

Features: *`r paste(features)`*

```{r,results='asis',echo=FALSE, fig.width=10, warning=FALSE}
for(i in features){
   featsum(i,dir)
}
```


