################################################################
#
# Pipeline pipeline_enumerate.py configuration file
#
################################################################

################################################################
#
# General options
#
################################################################
General:
  contig_dir: "/gfs/devel/majackson/Pipelines/MetaSequencing/testfiles/Assemble/contigs.dir/metaspades"
  gtf_dir: "/gfs/devel/majackson/Pipelines/MetaSequencing/testfiles/Annotate/combined_annotations.dir"
  #features to count from the taxonomic and functional annotations
  feature_list: "domain,phylum,class,order,family,genus,species,Predicted_protein_name,Gene_Ontology_terms,EC_number,KEGG_ko,KEGG_Pathway,KEGG_Module,KEGG_Reaction,BRITE,BiGG_Reaction,eggNOG_OGs,COG_Functional_Category"
  #features to count combined eg. species + predicted gene name will count genes split by species
  #provide as comma seperated list with pairs split by colons
  feature_pairs: "Predicted_protein_name:species,Predicted_protein_name:genus"
  #count TPMs? will normalise gene level counts to TPMs and then generate collapsed TPMs for features as above
  tpm: "true"
  #How to handle counts when a gene is mapped to multiple annotations of a feature (for instance a gene annotated with multiple GO terms).
  #"whole" will add the whole gene count to every annotation, "split" will divide the count across the features
  multimethod: "split"

  
################################################################
#
# Bowtie options
#
################################################################
BowtieDB:
  memory: "1"
  threads: "10"
  seed: "4"

Bowtie:
    #only use skip file prep if there is a crash of bowtie after a previous file prep
  skip_file_prep: "false"
  phred_type: "33"
#alignment mode (end-to-end or local) (NOTE: CHANGE MA & SCORE_MIN ALSO)
  mode: "end-to-end"
#preset settings (use this to input one of bowties presets as appropriate for the alignment mode e.g. very-fast)
#this overrides the manual settings below if not false
  preset: "false"
  n: "0"
  l: "22"
  i: "S,1,1.15"
  n_ceil: "L,0,0.15"
  dpad: "15"
  gbar: "4"
  ignore_quals: "false"
  nofw: "false"
  norc: "false"
  no_1mm_upfront: "false"
  ma: "0"
  mp: "6"
  np: "1"
  rdg: "5,3"
  rfg: "5,3"
  score_min: "L,-0.6,-0.6"
  #reporting mode default = best, k <int>  =  number of alns, a: "all"
  reporting: "k 1"
  d: "15"
  r: "2"
  minins: "0"
  maxins: "500"
  no_mixed: "false"
  no_discordant: "false"
  no_dovetail: "false"
  no_contain: "false"
  no_overlap: "false"
  threads: "10"
  memory: "1"

################################################################
#
# FeatureCounts Options
#
################################################################
featureCounts:
#number of chunks to divide GTF file (set as 1 for no chunking, can increase speed for very large GTFs)
  chunk: "2"
  f: "GTF"
  t: "ORF"
  o: "true"
  minoverlap: "1"
  fracoverlap: "0"
  fracoverlapfeature: "0"
  largestoverlap: "false"
  readextension5: "false"
  readextension3: "false"
  read2pos: "false"
  m: "true"
  fraction: "false"
  s: "0"
#set p true to count fragments instead of reads
  p: "true"
  b: "false"
  c: "false"
  threads: "20"
  memory: "3"
  v: "false"
  tmp: "/gfs/scratch/"
  threads_otherfeats: "15"
  memory_otherfeats: "1"

report:
  memory: "20"
  threads: "10"
